language: python
python:
  - "2.7"
install: "pip install ."
before_install:
  - pip install --target=.lib --ignore-installed 'about>=4.0.0'
install: "pip install ."
# command to run tests
script: "python setup.py test"
